IF EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'dbo.GenericScreen_SpFund_SavingPlans')
		)
	DROP VIEW dbo.GenericScreen_SpFund_SavingPlans
GO

/* Chagne log */
-- Changed to work with periodic orders
CREATE VIEW dbo.GenericScreen_SpFund_SavingPlans
AS
SELECT DISTINCT SPS_PERIODIC_ID AS PrimaryID
	,SPS_PERIODIC_ID AS SavingsID
	,TRX_CUSTOMER_FIRSTNAME AS FirstName
	,TRX_CUSTOMER_LASTNAME AS LastName
	,TRX_CUSTOMER_PERSONALID AS PersonalID
	,SPS_PERIODIC_NAME AS SavingsName
	,SPS_PERIODIC_CUSTOMFIELD2 AS SalesPerson
	,GO_DEPARTMENT_EXTERNALID AS DepartmentExternalID
	,GO_CONTACTINFO_NAME AS IncentiveUser
	,TRX_DISTRIBUTOR_NAME AS Distributor
	,SP.GO_USER_ID AS CreatedByUserID
	,SP.TRX_PORTFOLIO_ID AS PortfolioID
	,PORT.AXYS_PORTFOLIO_ID AS ExtPortID
	,SP.TRX_AGREEMENT_ID AS AgreementID
	,TRC_PAYMENTTYPE_NAME AS PaymentType
	,TRX_CUSTOMERACCOUNT_NUMBER AS CustomerAccountNR
	,SPS_PERIODIC_STARTDATE AS StartDate
	,SPS_PERIODIC_ENDDATE AS LastDate
	,SP.GO_USER_LASTUPDATED_BY_ID AS LastUpdateByUser
	,SPS_PERIODIC_REFERENCE AS Refrence
	,SPS_PERIODIC_COMMENT AS Comment
	,SPS_PERIODIC_EXTERNALID AS SavingExtID
	,SPS_PERIODIC_ENDDATE AS StopDate
	,SP.TRX_EXCHANGEACCOUNT_ID AS ExchangeAccountId
	,SPS_PERIODIC_MONTHS AS Months
	,MO.TRT_MODELORDER_ID AS ModelID
	,MO.TRT_MODELORDER_NAME AS ModelName
FROM SPS_PERIODIC SP
INNER JOIN TRX_PORTFOLIO PORT ON SP.TRX_PORTFOLIO_ID = PORT.TRX_PORTFOLIO_ID
INNER JOIN TRX_CUSTOMER C ON PORT.TRX_CUSTOMER_ID = C.TRX_CUSTOMER_ID
INNER JOIN TRC_PAYMENTTYPE PM ON SP.TRC_PAYMENTTYPE_ID = PM.TRC_PAYMENTTYPE_ID
INNER JOIN TXI_USERSHARING US ON SP.SPS_PERIODIC_ID = US.TXI_USERSHARING_FOREIGNKEY
	AND US.TXI_USERSHARING_TABLE = 'SPS_PERIODIC'
INNER JOIN GO_USER U ON U.GO_USER_ID = US.GO_USER_ID
INNER JOIN GO_CONTACTINFO CON ON CON.GO_CONTACTINFO_ID = U.GO_CONTACTINFO_ID
INNER JOIN TRX_DISTRIBUTOR D ON D.TRX_DISTRIBUTOR_ID = US.TRX_DISTRIBUTOR_ID
INNER JOIN GO_DEPARTMENT DEPT ON DEPT.GO_DEPARTMENT_ID = US.GO_DEPARTMENT_ID
LEFT OUTER JOIN TRX_CUSTOMERACCOUNT CA ON CA.TRX_CUSTOMERACCOUNT_ID = SP.TRX_CUSTOMERACCOUNT_ID
LEFT OUTER JOIN TRT_MODELORDER MO ON MO.TRT_MODELORDER_ID = SP.TRT_MODELORDER_ID
GO


